### ISSUE TITLE
Error: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by GhEllie** [ghidoz/angular2-jsonapi#17]
Hi there ,

I used JsonApi with RC2 and it worked fine . I hace upgraded my project to RC5 and after that I have a problem with using JsonApiDatastoreConfig objects.
I have a class like this:
@Injectable()
@JsonApiDatastoreConfig({
    baseUrl: 'http://localhost:9010/datasets/',
    models: {
        dataset: MarketTradeDataset,
        datasetSpecifications: DatasetSpecification,
        marketTradeDatasetItems: MarketTradeDatasetItem,
        markets: Market
    }
})
export class DataSetDatastore extends JsonApiDatastore {
}

when I want to inject this class to one my services I have the below error:
main.ts:78 TypeError: Cannot read property 'type' of null
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13673:45)
    at Array.forEach (native)
    at getTransitiveModules (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13672:17)
    at CompileMetadataResolver._getTransitiveNgModuleMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13387:37)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13259:47)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13228:58)
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13215:48)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:13228:58)
    at Array.forEach (native)

I tried to add JsonApiDatastore, JsonApiDatastoreConfig to my module.ts but I still have the same error.
Is anyone use this library with RC5?

**Comment by ghidoz** [comment]
Which version of angular2-jsonapi are you using?

**Comment by GhEllie** [comment]
"3.0.0"

**Comment by ghidoz** [comment]
Have you decorated each attribute of your models with the `Attribute()` decorator?

**Comment by ghidoz** [comment]
See these [BREAKING CHANGES](https://github.com/ghidoz/angular2-jsonapi/blob/master/CHANGELOG.md#breaking-changes)

**Comment by GhEllie** [comment]
I try to import {JsonApiModule} from 'angular2-jsonapi';  at the top of my main.ts file before all angular2 imports and it works fine now 

There should be a conflict in libraries using in JsonApi and Angular2

**Comment by ghidoz** [comment]
Closing this, as there is already #13 open about this issue.
