### ISSUE TITLE
Error during run test on Jest

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [ghidoz/angular2-jsonapi#209]
After migrate from karma to jest i get error:
```
Test suite failed to run

    /Users/przemyslawpietrzak/code/espeo/trade.io-eduportal/frontend/node_modules/lodash-es/find.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createFind from './_createFind.js';


    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/angular2-jsonapi/src/models/json-api.model.ts:1:1)
```

**Comment by WillGeller** [comment]
@ghidoz I am running into the same issue, any thoughts on solution?

**Comment by WillGeller** [comment]
I found this S.O. thread but it is inconclusive https://stackoverflow.com/questions/57222538/test-suite-failed-to-run-syntax-error-unexpected-identifier

**Comment by userann** [comment]
if I remember right....to work along with json api, I created that _mocks_ folder, created angular2-jsonapi.ts file and mocked JsonApiModel...like this(i think, not sure but you can try):

![image](https://user-images.githubusercontent.com/6122363/70786459-5dd82380-1d95-11ea-93c5-f67ab00383e2.png)

**Comment by sean-clayton** [comment]
Running into this issue as well.
