### ISSUE TITLE
Does not export JsonApiDatastoreConfig

### ISSUE THREAD

**Issue by listepo** [ghidoz/angular2-jsonapi#25]
Hi, I'm use `angular2-jsonapi@3.1.1`

```
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Mac OS X El Capitan
Node Version: v6.7.0
```

and have error

```
[15:13:13]  bundle dev failed:  Module /Users/ivan/github/Mush/node_modules/angular2-jsonapi/dist/index.js does not export JsonApiDatastoreConfig (imported by /Users/ivan/github/Mush/src/services/datastore.ts)

[15:13:13]  Error: Module /Users/ivan/github/Mush/node_modules/angular2-jsonapi/dist/index.js does not export JsonApiDatastoreConfig (imported by /Users/ivan/github/Mush/src/services/datastore.ts)
    at Module.trace (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:7706:29)
    at ModuleScope.findDeclaration (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:7329:22)
    at Scope.findDeclaration (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5349:39)
    at CallExpression.bind (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5834:28)
    at /Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5149:50
    at ArrayExpression.eachChild (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5163:19)
    at ArrayExpression.bind (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5149:7)
    at /Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5149:50
    at CallExpression.eachChild (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5163:19)
    at CallExpression.bind (/Users/ivan/github/Mush/node_modules/rollup/dist/rollup.js:5149:7)
```

**Comment by ghidoz** [comment]
Hi! Please, try to upgrade to v3.2.1 and see if it works!

**Comment by listepo** [comment]
Hi, now new error 
```
[18:18:46]  bundle update failed: 'JsonApiDatastoreConfig' is not exported by node_modules/angular2-jsonapi/dist/index.js
            (imported by src/services/datastore.ts). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
```

**Comment by ghidoz** [comment]
The new v3.4.0 should fix it.

Tested with:
- angular-cli@1.0.0-beta.22-1
- @angular/*@2.2.3

Please, let me know if it actually fixes.

**Comment by listepo** [comment]
Hi, thanks for the feedback, but it's a bug for me is no longer relevant. I have no able to verify right now.
